language: python

python:
  - "3.5"

script:
  - cd server
  - python3 -c "print(__import__('sqlite3').sqlite_version)"
  - python3 test_processors.py
  - python3 test_request_handler.py

notifications:
  email: false
